function createfigure(XData1, YData1)
%CREATEFIGURE(XDATA1, YDATA1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata

%  Auto-generated by MATLAB on 27-Feb-2016 11:33:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);

% Create line
line(XData1,YData1,'Parent',axes1,'Color',[0 0 1]);

